package com.example.insectopedia.model

class DefinedInsects {
    companion object {
        val insects = mapOf(
            "aphid" to "https://en.wikipedia.org/wiki/aphid",
            "bark beetle" to "https://en.wikipedia.org/wiki/bark_beetle",
            "bed bug" to "https://en.wikipedia.org/wiki/bed_bug",
            "beetle" to "https://en.wikipedia.org/wiki/beetle",
            "bee" to "https://en.wikipedia.org/wiki/bee",
            "bombyx mori" to "https://en.wikipedia.org/wiki/bombyx_mori",
            "botfly" to "https://en.wikipedia.org/wiki/botfly",
            "bumblebee" to "https://en.wikipedia.org/wiki/bumblebee",
            "butterfly" to "https://en.wikipedia.org/wiki/butterfly",
            "caddisfly" to "https://en.wikipedia.org/wiki/caddisfly",
            "caterpillar" to "https://en.wikipedia.org/wiki/caterpillar",
            "centipede" to "https://en.wikipedia.org/wiki/centipede",
            "cicada" to "https://en.wikipedia.org/wiki/cicada",
            "clothes moth" to "https://en.wikipedia.org/wiki/clothes_moth",
            "coccinellidae" to "https://en.wikipedia.org/wiki/coccinellidae",
            "cockroach" to "https://en.wikipedia.org/wiki/cockroach",
            "colorado potato beetle" to "https://en.wikipedia.org/wiki/colorado_potato_beetle",
            "cricket" to "https://en.wikipedia.org/wiki/cricket_(insect)",
            "damselfly" to "https://en.wikipedia.org/wiki/damselfly",
            "dragonfly" to "https://en.wikipedia.org/wiki/dragonfly",
            "drone" to "https://en.wikipedia.org/wiki/drone_(bee)",
            "dung beetle" to "https://en.wikipedia.org/wiki/dung_beetle",
            "earwing" to "https://en.wikipedia.org/wiki/earwig",
            "flea" to "https://en.wikipedia.org/wiki/flea",
            "fly" to "https://en.wikipedia.org/wiki/fly",
            "glowworm" to "https://en.wikipedia.org/wiki/glowworm",
            "gnat" to "https://en.wikipedia.org/wiki/gnat",
            "grasshopper" to "https://en.wikipedia.org/wiki/grasshopper",
            "hornet" to "https://en.wikipedia.org/wiki/hornet",
            "horse fly" to "https://en.wikipedia.org/wiki/Horse-fly",
            "house fly" to "https://en.wikipedia.org/wiki/Housefly",
            "housefly" to "https://en.wikipedia.org/wiki/Housefly",
            "ladybird" to "https://en.wikipedia.org/wiki/Coccinellidae",
            "lady bird" to "https://en.wikipedia.org/wiki/Coccinellidae",
            "lady bug" to "https://en.wikipedia.org/wiki/Coccinellidae",
            "ladybug" to "https://en.wikipedia.org/wiki/Coccinellidae",
            "locust" to "https://en.wikipedia.org/wiki/locust",
            "louse" to "https://en.wikipedia.org/wiki/louse",
            "mantis" to "https://en.wikipedia.org/wiki/mantis",
            "mayfly" to "https://en.wikipedia.org/wiki/mayfly",
            "midge" to "https://en.wikipedia.org/wiki/midge",
            "mosquito" to "https://en.wikipedia.org/wiki/mosquito",
            "moth" to "https://en.wikipedia.org/wiki/moth",
            "phyllophaga" to "https://en.wikipedia.org/wiki/phyllophaga",
            "pupa" to "https://en.wikipedia.org/wiki/pupa",
            "pyrrhocoridae" to "https://en.wikipedia.org/wiki/pyrrhocoridae",
            "sandfly" to "https://en.wikipedia.org/wiki/sandfly",
            "scorpion" to "https://en.wikipedia.org/wiki/scorpion",
            "slug" to "https://en.wikipedia.org/wiki/slug",
            "snail" to "https://en.wikipedia.org/wiki/snail",
            "spider" to "https://en.wikipedia.org/wiki/spider",
            "termite" to "https://en.wikipedia.org/wiki/termite",
            "wasp" to "https://en.wikipedia.org/wiki/wasp",
            "woodlouse" to "https://en.wikipedia.org/wiki/woodlouse",
        )

        val popularInsects = mapOf(
            "bee" to "https://en.wikipedia.org/wiki/bee",
            "ant" to "https://en.wikipedia.org/wiki/ant",
        )
    }
}